[tool.poetry]
name = "sa2schema"
version = "0.1.0"
description = "Convert SqlAlchemy models to Pydantic"
authors = ["Mark Vartanyan <kolypto@gmail.com>"]
repository = 'https://github.com/kolypto/py-sa2schema'

[tool.poetry.dependencies]
python = "^3.7"
sqlalchemy = "^1.3.0"
pydantic = {version = "^1.5", optional = true}

[tool.poetry.dev-dependencies]
pytest = "^5.2"
nox = "^2020.5.24"
pydantic = "^1.5"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
