name: Tests
on:
  # https://help.github.com/en/actions/reference/events-that-trigger-workflows
  pull_request:
    types: [ opened, edited, reopened ]
  release:
    types: [ prereleased , released ]
  push:
    branches: [ master ]
jobs:
  tests:
    runs-on: ubuntu-latest
    #container:

    strategy:
      matrix:
        python-version: ['3.x']#, 'pypy3']

    name: ${{ github.ref }}, Python ${{ matrix.python-version }}
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: ./.nox/  # what we cache: nox virtualenv (they're expensive)
        key: ${{ runner.os }}-nox-2-${{ matrix.python-version }}-${{ hashFiles('**/pyproject.toml', '**/noxfile.py') }}  # cache key
        restore-keys: |
          ${{ runner.os }}-nox-2-${{ matrix.python-version }}-
    - run: pip install poetry nox
    - run: nox --report nox-report.json
